### ISSUE TITLE
missing 'TrafficPacket_m.h' file

### ISSUE THREAD

**Issue by mfrey** [des-testbed/libara#124]
There seems to be an issue while building libARA. Usually the ``opp_msgc`` command creates out of a ``*.msg`` file the necessary header and source files. However, this seems to fail for the ``TrafficPacket.msg`` (in an automatic way) resulting in an ``missing file`` error.

```
netpp/traffic/TrafficGenerator.cpp
omnetpp/traffic/TrafficGenerator.cpp:7:10: fatal error: 
      'TrafficPacket_m.h' file not found
#include "TrafficPacket_m.h"
         ^
1 error generated.
make: *** [out/clang-debug/omnetpp/traffic/TrafficGenerator.o]
```

**Comment by mfrey** [comment]
The issue might be related to an issue in the corresponding version of automake (seems not to occur with gnue make 4.1, but with 3.81)

**Comment by mfrey** [comment]
I can finally confirm that this is an issue with gnu make. The build process works fine with all versions of gnu make >= 3.82. Unfortunately this seems to effect of debian wheezy. A simple workaround is to generate the file by yourself using the ``opp_msgc`` tool or to install gnu make in version 3.82 or higher.
